### ISSUE TITLE
Arctis Nova 7 Not Detected

### ISSUE THREAD

**Issue by OverSmoggy** [crazyklatsch/Arctis7_BatteryReader_rs#1]
I've got an Arctis Nova 7, but the app doesn't seem to recognize it

**Comment by crazyklatsch** [comment]
Yes that is expected since it identifies the arctis7 using its vendorID (VID) and productID (PID). And since every different product has a different PID the Nova 7 doesn't get recognized. To include it, we would need its PID and the information about the communication protocol (if the addresses are the same etc.).

**Comment by crazyklatsch** [comment]
If we find out the PID of the Arctis Nova 7 we can simply try if the protocol is the same

**Comment by cooldisorganizedmodern** [comment]
I have the Arctis Nova 7. Let me know how I can help in order to make this headset support your app

**Comment by crazyklatsch** [comment]
@HypeGameMode 
First, we need to identify the headset using the vid and pid. When the headset is connected, they can be found somewhere in windows device manager **OR** if you have rust installed you could make a new project:

`cargo init hid-device-helper`
`cd hid-device-helper`
`cargo add hidapi`

**main.rs**:
```
use hidapi::HidApi;

fn main() {
    match HidApi::new() {
        Ok(api) => {
            for device in api.device_list() {
                println!(
                    "{:04x}:{:04x} {} {}",
                    device.vendor_id(),
                    device.product_id(),
                    device.manufacturer_string().unwrap_or(""),
                    device.product_string().unwrap_or("")
                );
            }
        }
        Err(e) => {
            eprintln!("Error: {}", e);
        }
    }
}
```
and then check the output of `cargo run` for the nova headset.
_(e.g. I get this line somewhere in the output: `1038:12ad SteelSeries  SteelSeries Arctis 7` where 0x1038 is the vid and 0x12ad is the pid)_

**Comment by Giton22** [comment]
> @HypeGameMode First, we need to identify the headset using the vid and pid. When the headset is connected, they can be found somewhere in windows device manager **OR** if you have rust installed you could make a new project:
> 
> `cargo init hid-device-helper` `cd hid-device-helper` `cargo add hidapi`
> 
> **main.rs**:
> 
> ```
> use hidapi::HidApi;
> 
> fn main() {
>     match HidApi::new() {
>         Ok(api) => {
>             for device in api.device_list() {
>                 println!(
>                     "{:04x}:{:04x} {} {}",
>                     device.vendor_id(),
>                     device.product_id(),
>                     device.manufacturer_string().unwrap_or(""),
>                     device.product_string().unwrap_or("")
>                 );
>             }
>         }
>         Err(e) => {
>             eprintln!("Error: {}", e);
>         }
>     }
> }
> ```
> 
> and then check the output of `cargo run` for the nova headset. _(e.g. I get this line somewhere in the output: `1038:12ad SteelSeries SteelSeries Arctis 7` where 0x1038 is the vid and 0x12ad is the pid)_

1038:2202 SteelSeries Arctis Nova 7

**Comment by crazyklatsch** [comment]
@Giton22 @HypeGameMode 
I released v1.1.0 which should be able to identify the Arctis Nova 7. Please let me know, if reading the battery works.
If the "red X" icon stays when the headset is turned on and the mouse-over sais "Arctis Nova7 battery reader", then reading the battery doesn't work. If the mouse-over text just sais "Steelseries battery reader", then the headset is not identified.
When installing using the .msi from the release, the program can now be found and launched by searching for Arctis7-batteryreader-rs in the Windows search bar. (don't forget to manually stop the program if you have it running before installing the new version)

I'm looking forward to your feedback :D

**Comment by cooldisorganizedmodern** [comment]
![image](https://github.com/crazyklatsch/Arctis7_BatteryReader_rs/assets/81685371/568001f9-4053-4f8b-a2c4-9dc94ba9b3b9)
Nope. still not working

**Comment by Giton22** [comment]
This electron app can Identify and read the Arctis Nova 7 battery, maybe you can get some ideas from it.

https://github.com/richrace/arctis-monitor

**Comment by crazyklatsch** [comment]
Nice, thank you for the reference!
I don't know, when i will get to actually implementing something.
Until then, I'm open for a merge request.

**Comment by crazyklatsch** [comment]
I identified the problem (based on your nice reference) and am working on it. Will ping you, when i have it released.

**Comment by crazyklatsch** [comment]
@Giton22 @HypeGameMode @OverSmoggy 
Can you try again with the newest release (1.2.0) please.
Just as a warning: when reading the code from the electron app it seems that the nova headsets only report up to 5 battery levels (0%, 25%, 50%, 75%, 100%). I copied the calculation, so you should see only those values.

**Comment by Giton22** [comment]
It's still a red X writing "Steelseries battery reader" and after some seconds its automatically closing

**Comment by crazyklatsch** [comment]
Thank you for testing!
Ok, that means that the program terminates when trying to read the battery.
I'm assuming it has to do with the report lengths. I'll try to look into that soon :)

**Comment by Giton22** [comment]
If you want we can do some faster testing on discord for example. So you dont have to upload it to GH.
IIRC the report length is doubled.

**Comment by Giton22** [comment]
Little bit off topic, checked it myself in GO and I don't understand why there's 3 Steelseries Arctis Nova 7 with different paths. Do you have any idea?
![image](https://github.com/crazyklatsch/Arctis7_BatteryReader_rs/assets/24484823/0209a5fe-1ff0-4b99-93ba-4d914469d930)

**Comment by Giton22** [comment]
`	devices := hid.Enumerate(4152, 8706)
	device, err := devices[0].Open()
	if err != nil {
		fmt.Println(err)
		return
	}
	report, err := device.Write([]byte{0x00, 0xb0})
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(report)
`

this is my code and the results are (at 0-2 index):
![image](https://github.com/crazyklatsch/Arctis7_BatteryReader_rs/assets/24484823/f53b2d00-4560-4115-8e19-8395d4cbc9f9)

**Comment by Giton22** [comment]
Wait.. I built your app from source and its working 
![image](https://github.com/crazyklatsch/Arctis7_BatteryReader_rs/assets/24484823/8685c9db-e949-4353-af20-9ef248f0a5d0)

**Comment by crazyklatsch** [comment]
> If you want we can do some faster testing on discord for example. So you dont have to upload it to GH.
> IIRC the report length is doubled.

Hey @Giton22 I'd love to do that at some point.
At the moment I'm pretty busy irl, but I'll come back to you. You can add me on discord (same name/same profile pic as GitHub)
